[workspace]
members = ["ctru-rs", "ctru-sys"]

[patch.crates-io]
# We have some changes not in the upstream
libc = { git = "https://github.com/Meziu/libc.git" }

[patch.'https://github.com/Meziu/ctru-rs']
# Make sure all dependencies use the local ctru-sys package
ctru-sys = { path = "ctru-sys" }