[package]
name = "ctru-rs"
version = "0.1.1"
description = "A safe wrapper around smealum's ctrulib."
authors = ["Ronald Kinard <furyhunter600@gmail.com>", "FenrirWolf <fenrirwolf@gmail.com>"]
links = "ctru"
build = "build.rs"
license = "https://en.wikipedia.org/wiki/Zlib_License"

[lib]
name = "ctru"
crate-type = ["rlib"]
