[package]
name = "ctru-sys"
version = "22.0.0+2.2.0"
authors = [ "Rust3DS Org", "Ronald Kinard <furyhunter600@gmail.com>" ]
license = "Zlib"
links = "ctru"
edition = "2021"

[dependencies]
libc = { version = "0.2.121", default-features = false }

[build-dependencies]
which = "4.4.0"
