[package]
name = "ctru-sys"
version = "22.2.0+2.2.2-1"
authors = ["Rust3DS Org", "Ronald Kinard <furyhunter600@gmail.com>"]
license = "Zlib"
links = "ctru"
edition = "2021"

[dependencies]
libc = { version = "0.2.121", default-features = false }

[build-dependencies]
bindgen = { version = "0.65.1", features = ["experimental"] }
cc = "1.0"
doxygen-rs = "0.4.2"
which = "4.4.0"
