[package]
name = "ctru-sys"
version = "0.4.0"
authors = ["Ronald Kinard <furyhunter600@gmail.com>"]
license = "https://en.wikipedia.org/wiki/Zlib_License"
links = "ctru"

[dependencies]
libc = { version = "0.2", default-features = false }
linker-fix-3ds = { git = "https://github.com/Meziu/rust-linker-fix-3ds.git" }
