[package]
name = "ctru-sys"
version = "0.4.1"
authors = ["Ronald Kinard <furyhunter600@gmail.com>"]
license = "https://en.wikipedia.org/wiki/Zlib_License"
links = "ctru"
edition = "2021"

[dependencies]
libc = { version = "0.2.121", default-features = false }
doxygen-rs = { git = "https://github.com/Techie-Pi/doxygen-rs.git", version = "0.2.2", rev = "573f483ad63ab4662650961998d3ed093a703983", optional = true }

[features]
build-binary = ["doxygen-rs"]

[[bin]]
name = "docstring-to-rustdoc"
required-features = ["build-binary"]
