[package]
name = "std"
version = "0.0.0"

[lib]
crate-type = ["rlib"]

[dependencies.alloc_system3ds]
git = "https://github.com/rust3ds/alloc_system3ds"

[dependencies.ctru-sys]
path = "../ctru-sys"

[dependencies.spin]
version = "0.4"
